-- ^ Espaco
-- ~ Delimitador de final de trigger
-- $ Delimitador de final de sql dentro de trigger
--
-- File generated with SQLiteStudio v3.0.6 on seg ago 17 15:25:03 2015
--
-- Text encoding used: windows-1252
--
PRAGMA foreign_keys = off;
--^BEGIN^ TRANSACTION;

-- Table: CFAESTAD
CREATE TABLE IF NOT EXISTS CFAESTAD (ID_CFAESTAD INTEGER UNIQUE, DT_ALT DATETIME, UF CHAR (2), DESCRICAO VARCHAR (40));

-- Table: AEANATUR
CREATE TABLE IF NOT EXISTS AEANATUR (ID_AEANATUR        INTEGER NOT NULL, DT_ALT             DATETIME, CODIGO             INTEGER, DESCRICAO          VARCHAR(40));

-- Table: CFACLIFO
CREATE TABLE IF NOT EXISTS CFACLIFO (ID_CFACLIFO INTEGER NOT NULL, ID_CFAAREAS INTEGER, ID_CFATPCLI INTEGER, ID_CFASTATU INTEGER, ID_SMAEMPRE INTEGER, DT_ALT DATETIME, CPF_CNPJ VARCHAR (18), IE_RG VARCHAR (18), NOME_RAZAO VARCHAR (60), NOME_FANTASIA VARCHAR (60), CODIGO_CLI INTEGER, CODIGO_FOR INTEGER, CODIGO_FUN INTEGER, CODIGO_USU INTEGER, CODIGO_TRA INTEGER, CLIENTE CHAR (1), FORNECEDOR CHAR (1), FUNCIONARIO CHAR (1), USUARIO CHAR (1), TRANSPORTADORA CHAR (1), OBS TEXT, PESSOA CHAR (1), ATIVO CHAR (1) NOT NULL DEFAULT '1', DT_ULT_COMPRA DATETIME, DT_RENOVACAO DATETIME, UNIQUE (ID_CFACLIFO ASC), UNIQUE (CPF_CNPJ ASC) ON CONFLICT REPLACE);

-- Table: CFACIDAD
CREATE TABLE IF NOT EXISTS CFACIDAD (ID_CFACIDAD INTEGER NOT NULL UNIQUE, ID_CFAESTAD INTEGER, DT_ALT DATETIME, DESCRICAO VARCHAR (40));

-- Table: AEAITENT
CREATE TABLE IF NOT EXISTS AEAITENT (
    ID_AEAITENT         INTEGER NOT NULL,
    ID_AEAENTRA         INTEGER NOT NULL,
    ID_AEAUNVEN         INTEGER NOT NULL,
    ID_AEAESTOQ         INTEGER NOT NULL,
    ID_AEAITNFS         INTEGER,
    ID_AEAITSAI         INTEGER,
    ID_CFANATOP         INTEGER NOT NULL,
    ID_AEAITPED         INTEGER,
    ID_AEACODOM         INTEGER,
    ID_AEACODST         INTEGER,
    ID_AEACODST_IPI     INTEGER,
    ID_AEACODST_PIS     INTEGER,
    ID_AEACODST_COFINS  INTEGER,
    GUID                CHAR(16) NOT NULL,
    DT_CAD              DATETIME,
    DT_ALT              DATETIME,
    DT_ENTRADA          DATE NOT NULL,
    SEQUENCIA           INTEGER,
    QUANTIDADE          REAL DEFAULT 0 NOT NULL,
    QTDE_DAT_VAL        REAL DEFAULT 0 NOT NULL,
    QTDE_CONFERIDO      REAL DEFAULT 0 NOT NULL,
    VL_MERCADORIA       REAL DEFAULT 0 NOT NULL,
    TIPO                CHAR(1) NOT NULL,
    TIPO_PRODUTO        CHAR(1) NOT NULL,
    TIPO_BAIXA          DCHAR(1) NOT NULL,
    OBS                 TEXT,
    FC_MERCADORIA_UN    REAL,
    FC_CT_COMP          REAL);

-- Table: CFATPCLI
CREATE TABLE IF NOT EXISTS CFATPCLI (
    ID_CFATPCLI        INTEGER,
    DT_ALT             DATETIME,
    CODIGO             INTEGER NOT NULL,
    DESCRICAO          VARCHAR(40) NOT NULL,
    DESC_ATAC_VISTA    REAL DEFAULT 0 NOT NULL,
    DESC_ATAC_PRAZO    REAL DEFAULT 0 NOT NULL,
    DESC_VARE_VISTA    REAL DEFAULT 0 NOT NULL,
    DESC_VARE_PRAZO    REAL DEFAULT 0 NOT NULL,
    DESC_SERV_VISTA    REAL DEFAULT 0 NOT NULL,
    DESC_SERV_PRAZO    REAL DEFAULT 0 NOT NULL,
    DESC_PROMOCAO      CHAR(1),
    VENDE_ATAC_VAREJO  CHAR(1));

-- Table: SMAUSUAR
CREATE TABLE IF NOT EXISTS SMAUSUAR (ID_SMAUSUAR INTEGER NOT NULL UNIQUE PRIMARY KEY, ID_SMAEMPRE INTEGER, ID_CFACLIFO INTEGER NOT NULL, ID_CBANUMCX INTEGER, GUID CHAR (16) NOT NULL, US_CAD VARCHAR (20), DT_CAD DATETIME, DT_ALT DATETIME, CT_INTEG INTEGER, NOME VARCHAR (60));

-- Table: CFASTATU
CREATE TABLE IF NOT EXISTS CFASTATU (
    ID_CFASTATU        INTEGER NOT NULL,
    DT_ALT             DATETIME,
    CODIGO             INTEGER NOT NULL,
    DESCRICAO          VARCHAR(40) NOT NULL,
    MENSAGEM           TEXT,
    BLOQUEIA           CHAR(1) NOT NULL,
    PARCELA_EM_ABERTO  CHAR(1),
    VISTA_PRAZO        CHAR(1));

-- Table: CFAAREAS
CREATE TABLE IF NOT EXISTS CFAAREAS (
    ID_CFAAREAS          INTEGER NOT NULL,
    GUID                 CHAR(16) NOT NULL,
    DT_ALT               DATETIME,
    CODIGO               INTEGER NOT NULL,
    DESCRICAO            VARCHAR(40) NOT NULL,
    DESC_ATAC_VISTA      REAL DEFAULT 0 NOT NULL,
    DESC_ATAC_PRAZO      REAL DEFAULT 0 NOT NULL,
    DESC_VARE_VISTA      REAL DEFAULT 0 NOT NULL,
    DESC_VARE_PRAZO      REAL DEFAULT 0 NOT NULL,
    DESC_SERV_VISTA      REAL DEFAULT 0 NOT NULL,
    DESC_SERV_PRAZO      REAL DEFAULT 0 NOT NULL,
    DESC_PROMOCAO        CHAR(1),
    PERC_REDUC_FAT_ATAC  REAL DEFAULT 0 NOT NULL,
    PERC_REDUC_FAT_VARE  REAL DEFAULT 0 NOT NULL);

-- Table: AEAENTRA
CREATE TABLE IF NOT EXISTS AEAENTRA (
    ID_AEAENTRA         INTEGER NOT NULL,
    ID_SMAEMPRE         INTEGER NOT NULL,
    ID_AEASERIE         INTEGER NOT NULL,
    ID_CFACLIFO         INTEGER NOT NULL,
    ID_AEANATUR         INTEGER,
    ID_AEANFSAI         INTEGER,
    GUID                CHAR(16) NOT NULL,
    DT_ALT              DATETIME,
    TIPO                CHAR(1) NOT NULL,
    SERIE               CHAR(3),
    NUMERO              INTEGER NOT NULL,
    DT_EMISSAO          DATE NOT NULL,
    DT_SAIDA            DATE NOT NULL,
    DT_ENTRADA          DATE NOT NULL,
    DT_ESTORNO          DATE,
    VL_MERCADORIA       REAL DEFAULT 0 NOT NULL,
    FC_VL_TOTAL         REAL,
    SITUACAO            INTEGER DEFAULT 0 NOT NULL,
    FECHADO             INTEGER DEFAULT 0 NOT NULL,
    TIPO_BAIXA          CHAR(1) NOT NULL,
    OBS                 TEXT,
    CHV_NFE             VARCHAR(50),
    TIPO_EMISSAO        CHAR(1),
    FINALIDADE          CHAR(1));

-- Table: SMAEMPRE
CREATE TABLE IF NOT EXISTS SMAEMPRE (
    ID_SMAEMPRE                 INTEGER NOT NULL,
    DT_ALT                      DATETIME,
    CODIGO                      INTEGER NOT NULL,
    NOME_RAZAO                  VARCHAR(60) NOT NULL,
    NOME_FANTASIA               VARCHAR(60),
    CPF_CGC                     VARCHAR(18));

-- Index: INDEX_AEAENTRA_NUMERO_ASC
CREATE INDEX IF NOT EXISTS INDEX_AEAENTRA_NUMERO_ASC ON AEAENTRA (NUMERO ASC);

-- Index: INDEX_CFAESTAD_ID_CFAESTAD_ASC
CREATE INDEX IF NOT EXISTS INDEX_CFAESTAD_ID_CFAESTAD_ASC ON CFAESTAD (ID_CFAESTAD ASC);

-- Index: INDEX_SMAUSUAR_NOME_ASC
CREATE INDEX IF NOT EXISTS INDEX_SMAUSUAR_NOME_ASC ON SMAUSUAR (NOME ASC);

-- Index: INDEX_CFACLIFO_NOME_RAZAO
CREATE INDEX IF NOT EXISTS INDEX_CFACLIFO_NOME_RAZAO ON CFACLIFO (NOME_RAZAO ASC);

-- Index: INDEX_CFACLIFO_CODIGO_CLI_ASC
CREATE INDEX IF NOT EXISTS INDEX_CFACLIFO_CODIGO_CLI_ASC ON CFACLIFO (CODIGO_CLI ASC);

-- Index: INDEX_SMAUSUAR_ID_CFACLIFO
CREATE INDEX IF NOT EXISTS INDEX_SMAUSUAR_ID_CFACLIFO ON SMAUSUAR (ID_CFACLIFO ASC);

-- Index: INDEX_CFACIDAD_DESCRICAO_ASC
CREATE INDEX IF NOT EXISTS INDEX_CFACIDAD_DESCRICAO_ASC ON CFACIDAD (DESCRICAO ASC);

-- Index: INDEX_CFACIDAD_ID_CFAESTAD_ASC
CREATE INDEX IF NOT EXISTS INDEX_CFACIDAD_ID_CFAESTAD_ASC ON CFACIDAD (ID_CFAESTAD ASC);

-- Index: INDEX_AEAENTRA_DT_ENTRADA_DESC
CREATE INDEX IF NOT EXISTS INDEX_AEAENTRA_DT_ENTRADA_DESC ON AEAENTRA (DT_ENTRADA DESC);

-- Index: INDEX_CFACLIFO_ID_CFACLIFO
CREATE INDEX IF NOT EXISTS INDEX_CFACLIFO_ID_CFACLIFO ON CFACLIFO (ID_CFACLIFO ASC);

-- Index: INDEX_CFAESTAD_DESCRICAO
CREATE INDEX IF NOT EXISTS INDEX_CFAESTAD_DESCRICAO ON CFAESTAD (DESCRICAO ASC);

-- Index: INDEX_CFACIDAD_ID_CFACIDAD
CREATE INDEX IF NOT EXISTS INDEX_CFACIDAD_ID_CFACIDAD ON CFACIDAD (ID_CFACIDAD ASC);

-- Index: INDEX_AEAENTRA_ID_CFACLIFO_ASC
CREATE INDEX IF NOT EXISTS INDEX_AEAENTRA_ID_CFACLIFO_ASC ON AEAENTRA (ID_CFACLIFO ASC);

-- Index: INDEX_CFACLIFO_CODIGO_TRA_DESC
CREATE INDEX IF NOT EXISTS INDEX_CFACLIFO_CODIGO_TRA_DESC ON CFACLIFO (CODIGO_TRA DESC);

-- Index: INDEX_AEAENTRA_DT_ENTRADA_ASC
CREATE INDEX IF NOT EXISTS INDEX_AEAENTRA_DT_ENTRADA_ASC ON AEAENTRA (DT_ENTRADA ASC);

-- Index: INDEX_CFACLIFO_CODIGO_TRA_ASC
CREATE INDEX IF NOT EXISTS INDEX_CFACLIFO_CODIGO_TRA_ASC ON CFACLIFO (CODIGO_TRA ASC);

-- Index: INDEX_AEAENTRA_NUMERO_DESC
CREATE INDEX IF NOT EXISTS INDEX_AEAENTRA_NUMERO_DESC ON AEAENTRA (NUMERO DESC);

-- Index: INDEX_SMAUSUAR_NOME_DESC
CREATE INDEX IF NOT EXISTS INDEX_SMAUSUAR_NOME_DESC ON SMAUSUAR (NOME DESC);

-- Index: INDEX_CFACLIFO_CODIGO_CLI_DESC
CREATE INDEX IF NOT EXISTS INDEX_CFACLIFO_CODIGO_CLI_DESC ON CFACLIFO (CODIGO_CLI DESC);

-- Index: INDEX_CFACLIFO_NOME_FANTASIA
CREATE INDEX IF NOT EXISTS INDEX_CFACLIFO_NOME_FANTASIA ON CFACLIFO (NOME_FANTASIA ASC);

-- Index: INDEX_CFAESTAD_UF_ASC
CREATE INDEX IF NOT EXISTS INDEX_CFAESTAD_UF_ASC ON CFAESTAD (UF ASC);

-- Index: INDEX_SMAUSUAR_ID_SMAUSUAR_ASC
CREATE INDEX IF NOT EXISTS INDEX_SMAUSUAR_ID_SMAUSUAR_ASC ON SMAUSUAR (ID_SMAUSUAR ASC);

--COMMIT TRANSACTION;
PRAGMA foreign_keys = on;